# Generated by Django 5.2.3 on 2025-09-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('CEO', 'CEO'), ('employee', 'Employee')], default='customer', max_length=20),
        ),
    ]
