# Generated by Django 5.2.3 on 2025-07-07 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_wallet', '0003_wallettransaction_processed_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallettransaction',
            old_name='user',
            new_name='customer',
        ),
    ]
