# Generated by Django 5.2.3 on 2025-07-12 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_wallet', '0004_rename_user_wallettransaction_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('wallet', 'Wallet'), ('other', 'Other')], max_length=50),
        ),
    ]
