# Generated by Django 5.2.3 on 2025-09-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_wallet', '0005_alter_wallettransaction_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='cumulative_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
