# Generated by Django 5.2.3 on 2025-09-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_wallet', '0006_wallettransaction_cumulative_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='cumulative_balance',
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
